### ISSUE TITLE
Using kube-dns doesn't resolve correctly.

### ISSUE THREAD

**Issue by jimmiebtlr** [Mashape/kong-dist-kubernetes#6]
## Setup
With the env variables 
```
        env:
          - name: KONG_DNS_RESOLVER
            value: 10.3.240.10
          - name: KONG_DNSMASQ
            value: "off"
         ...
```

Note 10.3.240.10 is the result of 

`kubectl get svc kube-dns --namespace=kube-system | grep kube-dns | awk '{print $2}'`

## Expected

```
    {
         "preserve_host" : false,
         "upstream_url" : "http://console-graphql-service/graphiql",
         "created_at" : 1481226046000,
         "strip_request_path" : true,
         "name" : "graphiql",
         "id" : "b3369902-e18b-4eb6-99d7-d3faef64a1c9",
         "request_path" : "/graphiql"
      }
```

Should resolve to the console-graphql-service.

## Actual 

```
Kong Error

An invalid response was received from the upstream server.
```

Note, substituting `console-graphql-service` in the api config with the service ip does return the expected result.
